{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta2
{{- end }}
kind: Deployment
metadata:
  name: {{ template "cp-kafka-connect.fullname" . }}
  labels:
    app: {{ template "cp-kafka-connect.name" . }}
    chart: {{ template "cp-kafka-connect.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "cp-kafka-connect.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "cp-kafka-connect.name" . }}
        release: {{ .Release.Name }}
      {{- if or .Values.podAnnotations .Values.jmx.prometheus.enabled .Values.datadog.jmx.enabled .Values.datadog.logs.enabled}}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- if .Values.jmx.prometheus.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.jmx.prometheus.port | quote }}
      {{- end }}
      {{- if .Values.datadog.jmx.enabled }}
        ad.datadoghq.com/{{ template "cp-kafka-connect.fullname" . }}.check_names: '["confluent_platform"]'
        ad.datadoghq.com/{{ template "cp-kafka-connect.fullname" . }}.init_configs: '[{"is_jmx":true,"collect_default_metrics":true}]'
        ad.datadoghq.com/{{ template "cp-kafka-connect.fullname" . }}.instances: |
          [
            {
              "host":"%%host%%",
              "port":{{ .Values.jmx.port | quote }},
              "max_returned_metrics":{{.Values.datadog.jmx.max_returned_metrics}}
            }
          ]
      {{- end }}
      {{- if .Values.datadog.logs.enabled }}
        ad.datadoghq.com/{{ template "cp-kafka-connect.fullname" . }}.logs: '[{"source":"confluent_platform","service":"confluent_platform"}]'
      {{- end }}
      {{- end }}
    spec:
      containers:
        {{- if .Values.jmx.prometheus.enabled }}
        - name: prometheus-jmx-exporter
          image: "{{ .Values.jmx.prometheus.image }}:{{ .Values.jmx.prometheus.imageTag }}"
          imagePullPolicy: "{{ .Values.jmx.prometheus.imagePullPolicy }}"
          command:
          - java
          - -XX:+UnlockExperimentalVMOptions
          - -XX:+UseCGroupMemoryLimitForHeap
          - -XX:MaxRAMFraction=1
          - -XshowSettings:vm
          - -jar
          - jmx_prometheus_httpserver.jar
          - {{ .Values.jmx.prometheus.port | quote }}
          - /etc/jmx-kafka-connect/jmx-kafka-connect-prometheus.yml
          ports:
          - containerPort: {{ .Values.jmx.prometheus.port }}
          resources:
{{ toYaml .Values.jmx.prometheus.resources | indent 12 }}
          volumeMounts:
          - name: jmx-config
            mountPath: /etc/jmx-kafka-connect
        {{- end }}
        - name: {{ template "cp-kafka-connect.fullname" . }}
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
            - name: kafka-connect
              containerPort: {{ .Values.servicePort}}
              protocol: TCP
            {{- if .Values.jmx.enabled }}
            - containerPort: {{ .Values.jmx.port }}
              name: jmx
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: {{ template "cp-kafka-connect.kafka.bootstrapServers" . }}
            - name: CONNECT_GROUP_ID
              value: {{ template "cp-kafka-connect.groupId" . }}
            {{ if not (hasKey .Values.configurationOverrides "config.storage.topic") }}
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: {{ template "cp-kafka-connect.fullname" . }}-config
            {{ end }}
            {{ if not (hasKey .Values.configurationOverrides "offset.storage.topic") }}
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: {{ template "cp-kafka-connect.fullname" . }}-offset
            {{ end }}
            {{ if not (hasKey .Values.configurationOverrides "status.storage.topic") }}
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: {{ template "cp-kafka-connect.fullname" . }}-status
            {{ end }}
            - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
              value: {{ template "cp-kafka-connect.cp-schema-registry.service-name" .}}
            - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
              value: {{ template "cp-kafka-connect.cp-schema-registry.service-name" .}}
            - name: KAFKA_HEAP_OPTS
              value: "{{ .Values.heapOptions }}"
            {{- range $key, $value := .Values.configurationOverrides }}
            - name: {{ printf "CONNECT_%s" $key | replace "." "_" | upper | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.customEnv }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.jmx.enabled }}
            - name: KAFKA_JMX_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KAFKA_JMX_PORT
              value: "{{ .Values.jmx.port }}"
            - name: KAFKA_JMX_OPTS
              value: >-
                -Djava.rmi.server.hostname=$(KAFKA_JMX_HOSTNAME)
                -Dcom.sun.management.jmxremote
                -Dcom.sun.management.jmxremote.authenticate=false
                -Dcom.sun.management.jmxremote.ssl=false
                -Dcom.sun.management.jmxremote.local.only=false
                -Dcom.sun.management.jmxremote.port={{ .Values.jmx.port }}
                -Dcom.sun.management.jmxremote.rmi.port={{ .Values.jmx.port }}
            {{- end }}
        {{- if .Values.customEnv.CUSTOM_SCRIPT_PATH }}
          command:
            - /bin/bash
            - -c
            - |
              /etc/confluent/docker/run &
              $CUSTOM_SCRIPT_PATH
              sleep infinity
        {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | trim | indent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | trim | indent 12 }}
          {{- end }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
{{ toYaml .Values.volumeMounts | indent 10 }}
          {{- end}}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.volumes }}
{{ toYaml .Values.volumes | trim | indent 6 }}
      {{- end}}
      {{- if .Values.jmx.prometheus.enabled }}
      - name: jmx-config
        configMap:
          name: {{ template "cp-kafka-connect.fullname" . }}-jmx-prometheus-configmap
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end -}}
      {{- if .Values.securityContext }}
      securityContext: {{- toYaml .Values.securityContext | nindent 10 }}
      {{- end }}
